/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.eltex;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.IOException;

/**
 * The type App.
 */
public class App {

    /**
     * The entry point of application.
     *
     * @param args the input arguments
     * @throws IOException the io exception
     */
    public static void main(String[] args) throws IOException {
        System.out.println("Users:");
        User myDefaultUser = new User();

        System.out.println(myDefaultUser.toString());
        User myUser = new User(111, "Petrov", "Petr", "88005553535", "Junior Android Developer");
        System.out.println(myUser.toString());

        System.out.println("---------------------------------------");
        System.out.println("Individual person:");

        Individual myDefaultIndividual = new Individual();
        System.out.println(myDefaultIndividual.toString());

        Individual myIndividual = new Individual(222, "Kirillov", "Kirill", "2132131", "Cleaner");
        System.out.println(myIndividual.toString());

        System.out.println("Company:");

        Company myDefaultCompany = new Company();
        System.out.println(myDefaultCompany.toString());

        Company myCompany = new Company(333, "Google", "Vadimov", "Vadim", "1232113", "Logist");
        System.out.println(myCompany.toString());

        System.out.println("---------------------------------------");
        System.out.println("Write to memory from file:");

        ObjectMapper mapper = new ObjectMapper();
        mapper.writeValue(new File("result.json"), myUser);

        User user1 = mapper.readValue(new File("result.json"), User.class);
        System.out.println(user1.toString());
    }
}
